name: Redirect Rule Maker

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: install python dependencies
        run: |
          pip install -r ${{ github.workspace }}/requirements.txt

      - name: Generate Config
        run : |
          python -u ${{ github.workspace }}/main.py

      - name: Commit Output
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
        with:
          source-directory: ./output/
          destination-github-username: 'xiaomage2000'
          destination-repository-name: 'oneinstack-redirect-mirror'
          user-email: 13915895+xiaomage2000@users.noreply.github.com
          target-branch: main
